// packages/vite-plugin-us/playground/react-ts/src/App.tsx
import { useState } from "react"
import reactLogo from "./assets/react.svg"
import viteLogo from "./assets/vite.svg"
import "./App.css"

function App() {
	const [count, setCount] = useState(0)
	console.log(typeof GM_xmlhttpRequest)
	console.log(typeof GM_info)
	return (
		<div className="App">
			<div>
				<a href="https://vitejs.dev" target="_blank">
					<img src={viteLogo} className="logo" alt="Vite logo" />
				</a>
				<a href="https://reactjs.org" target="_blank">
					<img src={reactLogo} className="logo react" alt="React logo" />
				</a>
			</div>
			<h1>Vite + React</h1>
			<div className="card">
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<p className="read-the-docs">
				Click on the Vite and React logos to learn more
			</p>
		</div>
	)
}

export default App

// packages/vite-plugin-us/example/vue-ts/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import HelloWorld from './components/HelloWorld.vue';
import viteLogoUrl from './assets/vite.svg?inline';
import vueLogoUrl from './assets/vue.svg?inline';
// import fastUrl from './assets/fast.jpg'
// import remote from 'https://vitejs.dev/logo.svg'


// GM_log('hello, world')

// console.log(typeof GM_xmlhttpRequest)
// console.log(GM_info)
// console.log(typeof (window as any).GM.setValue)
//@ts-ignore

</script>

<template>
  <div>
    <el-button type="primary">click</el-button>
    <a href="https://vitejs.dev" target="_blank">
      <img :src="viteLogoUrl" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img :src="vueLogoUrl" class="logo vue" alt="Vue logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <!-- <img :src="fastUrl" class="logo vue" alt="Vue logo" /> -->
    </a>
    <!-- <a href="https://vuejs.org/" target="_blank">
      <img :src="remote" class="logo vue" alt="Vue logo" />
    </a> -->
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
